<#============================================================================
  File:     B04525 - Ch10 - 00 - .ps1
  Author:   Donabel Santos (@sqlbelle | sqlbelle.com)
  Version:  SQL Server 2014, PowerShell V5
  Copyright: 2015
  ----------------------------------------------------------------------------

  This script is intended only as supplementary material to Packt's SQL Server 2014
  and PowerShell V5 book, and is downloadable from http://www.packtpub.com/
  
  THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF 
  ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED 
  TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
  PARTICULAR PURPOSE.
============================================================================#>

$reportServerUri  = "http://localhost/ReportServer/ReportService2010.asmx"
$proxy = New-WebServiceProxy -Uri $reportServerUri -UseDefaultCredential 

#get autogenerated namespace
$type = $proxy.GetType().Namespace

#specify which report's data source to change
$reportPath = "/Customer Reports/Customer Sales"

#look for the report in the catalog items array
#note we are using PowerShell V3 Where-Object syntax
$report = $proxy.ListChildren("/", $true) | 
          Where-Object Path -eq $reportPath

#get current data source name
#this needs to be the same name in the RDL
$dataSourceName  = $($proxy.GetItemDataSources($report.Path)).Name 

#specify new data source reference
$newDataSourcePath  = "/Data Sources/Sample"

#dynamically create data types based on the new
#autogenerated namespace
$dataSourceType = ($type + '.DataSource')
$numItems = 1
$dataSourceArrayType = ($type + '.DataSource[]')
$dataSourceReferenceType = ($type + '.DataSourceReference')

#create a data source array containing
#the new data source path
$dataSourceArray = New-Object ($datasourceArrayType)$numItems
$dataSourceArray[0] = New-Object ($dataSourceType)
$dataSourceArray[0].Name = $dataSourceName  
$dataSourceArray[0].Item = New-Object ($dataSourceReferenceType)
$dataSourceArray[0].Item.Reference = $newDataSourcePath

#set the new data source
$proxy.SetItemDataSources($report.Path, $dataSourceArray)
